# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ParcelEditor
                                 A QGIS plugin
 ParcelEditor
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-02
        copyright            : (C) 2026 by Joshua De Leon
        email                : assistantgisjosh@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ParcelEditor class from file ParcelEditor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .parcel_editor import ParcelEditor
    return ParcelEditor(iface)
