# -*- coding: utf-8 -*-
"""
/***************************************************************************
 practice_editor
                                 A QGIS plugin
 this is practice editor
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-05
        copyright            : (C) 2026 by joshdels
        email                : joshdels@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load practice_editor class from file practice_editor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .practice_editor import practice_editor
    return practice_editor(iface)
