# -*- coding: utf-8 -*-
"""
/***************************************************************************
 practice_editorDialog
                                 A QGIS plugin
 this is practice editor
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-05
        git sha              : $Format:%H$
        copyright            : (C) 2026 by joshdels
        email                : joshdels@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QFileDialog
from qgis.core import QgsProject, QgsVectorLayer, QgsRasterLayer, QgsMessageLog

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'practice_editor_dialog_base.ui'))


class practice_editorDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(practice_editorDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        self.btnAddFile.clicked.connect(self.add_file)
        self.btnAddBasemap.clicked.connect(self.add_basemap)
        
    def add_file(self):
        """Open file picker and add layer to map"""
        path, _ = QFileDialog.getOpenFileName(
            self,
            "Select vector file",
            "",
            "Vector layers (*.shp *.geojson);;All files (*.*)"
        )
        if not path:
            return

        # Try to load layer
        layer = QgsVectorLayer(path, os.path.basename(path), "ogr")
        if not layer.isValid():
            QgsMessageLog.logMessage(f"Failed to load layer: {path}", level=QgsMessageLog.CRITICAL, tag="MyPlugin")
            return

        QgsProject.instance().addMapLayer(layer)
        QgsMessageLog.logMessage(f"Layer added: {layer.name()}", tag="MyPlugin")

    def add_basemap(self):
        """Add OpenStreetMap basemap as XYZ Tile"""
        url = "type=xyz&url=https://tile.openstreetmap.org/{z}/{x}/{y}.png"
        basemap = QgsRasterLayer(url, "OpenStreetMap", "wms")
        if not basemap.isValid():
            QgsMessageLog.logMessage("Failed to load basemap", level=QgsMessageLog.CRITICAL, tag="MyPlugin")
            return

        QgsProject.instance().addMapLayer(basemap)
        QgsMessageLog.logMessage("OSM Basemap added", tag="MyPlugin")