# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'practice_editor_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnAddFile = QtWidgets.QPushButton(Dialog)
        self.btnAddFile.setObjectName("btnAddFile")
        self.verticalLayout.addWidget(self.btnAddFile)
        self.btnAddBasemap = QtWidgets.QPushButton(Dialog)
        self.btnAddBasemap.setObjectName("btnAddBasemap")
        self.verticalLayout.addWidget(self.btnAddBasemap)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnAddFile.setText(_translate("Dialog", "Add File"))
        self.btnAddBasemap.setText(_translate("Dialog", "Add Basemap"))
